name: Live Stream to Facebook

on:
  push:
    branches:
      - main  # التفعيل عندما تقومين بدفع التعديلات إلى الفرع الرئيس

jobs:
  deploy:
    runs-on: ubuntu-latest  # تشغيل على سيرفر Ubuntu في GitHub Actions
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Install FFmpeg
      run: sudo apt update && sudo apt install -y ffmpeg
    
    - name: Run live stream script
      run: |
        # إعدادات البث
        M3U8_URL="https://d3g87jnubafe6a.cloudfront.net/out/v1/1fa0fb3c8dec402994a6f7a7f6492b82/index_5.m3u8"  # رابط M3U8 الجديد
        STREAM_KEY="FB-684841160889136-0-Ab0dZL4j12AwfD8ku6SM9U3f"  # مفتاح البث الخاص بك
        FB_URL="rtmps://live-api-s.facebook.com:443/rtmp/$STREAM_KEY"

        # التحقق من توفر الرابط M3U8
        check_m3u8() {
          curl -s --head "$M3U8_URL" | grep "200 OK" > /dev/null
          return $?
        }

        # حلقة البث
        while true; do
          echo "التحقق من توفر رابط M3U8..."
          if ! check_m3u8; then
            echo "الرابط غير متوفر. إعادة المحاولة بعد 10 ثواني..."
            sleep 10
            continue
          fi

          echo "بدء البث على فيسبوك..."
          ffmpeg -re -i "$M3U8_URL" \
            -c:v copy -c:a aac -b:a 128k -f flv "$FB_URL" \
            2>> "ffmpeg_error.log"

          echo "حدث خطأ أثناء البث. إعادة التشغيل بعد 5 ثواني..."
          sleep 5
        done
